# Generated by Django 4.2.5 on 2023-09-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruze_social_media', '0002_comment_post_delete_content_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
