# Generated by Django 4.2.5 on 2023-09-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruze_social_media', '0003_rename_post_post_description_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
